{{- if .Values.iac.pulumi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-{{ .Values.stage }}-{{ .Values.region }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulumi-{{ .Values.stage }}-{{ .Values.region }}-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  namespace: {{.Release.Namespace}}
  name: pulumi-{{ .Values.stage }}-{{ .Values.region }}-sa
---
apiVersion: pulumi.com/v1
kind: Program
metadata:
  name: pu-program-{{ .Values.stage }}-{{ .Values.region }}
program:
  resources:
    app:
      type: digitalocean:App
      properties:
        spec:
          name: app-{{ .Values.stage }}-{{ .Values.region }}
          region: {{ .Values.region }}
          services:
          - name: app-service-{{ .Values.stage }}-{{ .Values.region }}
            instanceCount: 1
            instanceSizeSlug: "apps-s-1vcpu-1gb"
            git:
              repoCloneUrl: {{ .Values.app.repo }}
              branch: "main"
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: pu-stack-{{ .Values.stage }}-{{ .Values.region }}
spec:
  serviceAccountName: pulumi-{{ .Values.stage }}-{{ .Values.region }}-sa
  destroyOnFinalize: true
  envRefs:
    PULUMI_ACCESS_TOKEN:
      type: Env
      env:
        name: PULUMI_ACCESS_TOKEN
    DIGITALOCEAN_TOKEN:
      env:
        name: DIGITALOCEAN_TOKEN
      type: Env
  programRef:
    name: pu-program-{{ .Values.stage }}-{{ .Values.region }}
  stack: ediri/pu-program-{{ .Values.stage }}-{{ .Values.region }}/{{ .Values.stage }}
  workspaceTemplate:
    spec:
      image: pulumi/pulumi:3.152.0-nonroot
{{- end }}
