infra-chart:
  region: fra1
  stage: uat
  iac:
    pulumi:
      enabled: false
    crossplane:
      enabled: true
  #app:
    #repo: https://github.com/digitalocean/sample-vuejs
    #repo: https://github.com/digitalocean/sample-nextjs
