apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cd-summit-demo
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/dirien/kargo-test
      revision: HEAD
      directories:
      - path: stages/*
  template:
    metadata:
      name: cd-summit-demo-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: cd-summit-demo:*
    spec:
      project: default
      sources:
      - repoURL: https://github.com/dirien/kargo-test
        targetRevision: main
        path: stages/{{path.basename}}
        helm:
          valueFiles:
          - $values/stages/{{path.basename}}/values.yaml
      - repoURL: https://github.com/dirien/kargo-test
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: default #cd-summit-demo-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
