apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
spec:
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.sources[].targetRevision
  generators:
  - git:
      repoURL: https://github.com/dirien/kargo-test
      revision: HEAD
      directories:
      - path: stages/*
  template:
    metadata:
      name: demo-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: demo:*
    spec:
      project: default
      source:
        repoURL: https://github.com/dirien/kargo-test
        targetRevision: main
        path: stages/{{path.basename}}
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
