apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: argocon-demo
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: argocon-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: "https://github.com/dirien/kargo-test.git"
  username: "dirien"
  password: "xxx"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: infra-chart-warehouse
  namespace: argocon-demo
spec:
  freightCreationPolicy: Automatic
  interval: 30s
  subscriptions:
  - chart:
      discoveryLimit: 20
      name: infra-chart
      repoURL: https://dirien.github.io/kargo-test/
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: argocon-demo
spec:
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/test
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infra-chart-warehouse
    sources:
      direct: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: argocon-demo
spec:
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/uat
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infra-chart-warehouse
    sources:
      stages:
      - test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-nyc
  namespace: argocon-demo
spec:
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/prod-nyc
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infra-chart-warehouse
    sources:
      stages:
      - uat
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-ams
  namespace: argocon-demo
spec:
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/prod-ams
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infra-chart-warehouse
    sources:
      stages:
      - prod-nyc
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-lon
  namespace: argocon-demo
spec:
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        - name: stageFolder
          value: stages/prod-lon
  requestedFreight:
  - origin:
      kind: Warehouse
      name: infra-chart-warehouse
    sources:
      stages:
      - prod-nyc
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: argocon-demo
spec:
  vars:
  - name: repoURL
    value: https://github.com/dirien/kargo-test.git
  - name: helmRepoURL
    value: https://dirien.github.io/kargo-test/
  - name: branch
    value: main
  - name: stageFolder
    value: dev
  - name: chartName
    value: infra-chart
  steps:
  - uses: git-clone
    as: clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        create: true
        path: ./out
  - uses: helm-update-chart
    as: update-helm-chart-dependency
    config:
      path: ./out/${{ vars.stageFolder }}
      charts:
      - repository: ${{ vars.helmRepoURL }}
        name: ${{ vars.chartName }}
        version: ${{ chartFrom(vars.helmRepoURL,vars.chartName).Version }}
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: ${{ task.outputs['update-helm-chart-dependency'].commitMessage }}
  - uses: git-push
    config:
      path: ./out
      targetBranch: ${{ vars.branch }}
